### PR TITLE
feat(141); created a rest api client package

### PR DESCRIPTION
**Pull request by kharaone**
- the schemas generated were not found because they were leveraging component path. I changed it to use getModelSchemaRef
- leverage the OAS file to generate a typescript client package

### CODE REVIEW

**Comment by elijaholmos** [comment]
Code seems fine, but the `codegen` script errors on my end:
image

I also have a handful of IDE errors that can all be addressed at the next sync.

**Comment by kharaone** [comment]
@elijaholmos are you on mac or linux ? the && syntax is definitely for Powershell/windows environment.

**Comment by elijaholmos** [comment]
@kharaone windows CMD prompt. I will try powershell when I return later this evening

**Comment by elijaholmos** [comment]
same error :(

image

**Comment by kharaone** [comment]
@elijaholmos ok, it's due to the "mkdir part", since the folder already exists, it errors out. 
Also note that this sdk folder location isn't ideal as it's not within the rootDir of the main tsconfig AND it has its own package.json/tsconfig.json pair.
atm, I'm just using it to generate the package and don't need it to be persisted.

I'll probably swith to monorepo with multipackage in order to let it live nicely with the rest

**Pull request merged**
