### PR TITLE
get all entries for user

### PR DESCRIPTION
**Pull request by elijaholmos**
API implementation allowing a client to retrieve all GoodEntries for a given PoG user

point of discussion:
- what should the identifiable user information be? I am currently leveraging `userId`, but `doGooder` or even `walletAddresses` may be alternative options

### CODE REVIEW

**Comment by kharaone** [comment]
@elijaholmos userId is encompassing : email AND walletAddress. 
The contract uses the concep of userId which has an email, and walletAddresses associated. They are the pog-profiles. 
We should ultimately be able to resolve everything to a userId, starting from an email or a walletAddress. (ie, lookup the profile by email or walletAddress)

**Comment by kharaone** [comment]
Note that the contract has some interesting methods that we could leverage:
- `getUserIdProofOfGoodEntries(bytes32 _userId) public view returns(ProofOfGoodEntry[] memory)`
- `function getAddressCategoryBalances(address _account) public view returns(CategoryBalances[] memory)`

Thoughts : we should have the pog-api hit the ledger instead of reading the database. the website can read from the database though.

@gitluky @elijaholmos

**Comment by kharaone** [comment]
@elijaholmos for a normal endpoint of the pog-api, this implementation is enough. However, as the name of your branch is impliying, this is to display the #177 story, and therefore doesn't provide all the data required to display the "ledger" for a specific user:
- avatar, username are saved on the web2 side only
- category, type are resolved to their respective entry in order to get their names, etc

the backend work of that story should definitely be done on [leyline-gg/pog-monorepo](https://github.com/Leyline-gg/pog-monorepo/blob/production/packages/pog-api/src/functions/LedgerAPIService.ts#L180) instead

**Comment by elijaholmos** [comment]
transferring logic to pog-monorepo per discussion w Karim 2022-06-02

**Pull request closed without merging**
